# Exemplo: PCA 

In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

## Criando banco de dados

In [2]:
var_originals = pd.DataFrame({"A": [102,104,101,93,100], "B": [96,87,62,68,77]})

## Padronizando os dados

In [3]:
x = np.matrix(var_originals);x
#x = np.asarray(x);x

#Padronizando para media 0 e variancia 1
z_score_A = (var_originals-var_originals.mean())/var_originals.std(axis=0)
#z_score_A
#Padronizando para media qualquer e variancia 1
z_score_B = var_originals/var_originals.std(axis=0)
#z_score_B

## Matriz de correlação

In [4]:
correlation = z_score_B.corr()

## Obtendo os Autovetores e Autovalores

In [5]:
#Transformando a matriz de correlacao do tipo pandas no tipo matrix
data_corr = np.asmatrix(correlation);data_corr
#Obtendo os Autovalores e autovetores
autovalues, autovectors = np.linalg.eig(data_corr)

## Proporçao da variancia total explicada pelo i-esimo componente principal

In [11]:
var_expl = autovalues/sum(autovalues);var_expl

array([0.77278095, 0.22721905])

## Porcentagem acumulada de variancia dos Yi

In [13]:
cum_var_expl = np.cumsum(var_expl)*100; cum_var_expl

array([ 77.27809539, 100.        ])

## Obtendo os scores

In [6]:
np.matmul(autovectors.T, np.matrix(z_score_B).T)
#P = autovectors.T.dot(z_score_B.T)
#print(P.T)

matrix([[ 22.15937578,  22.03635352,  20.24847217,  19.20361467,
          20.8479146 ],
        [-12.32291781, -13.12206348, -13.89575972, -12.2361236 ,
         -12.95825559]])