# Exemplo: PCA 

In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

## Criando banco de dados

In [2]:
var_originals = pd.DataFrame({"A": [102,104,101,93,100], "B": [96,87,62,68,77]})

## Padronizando os dados

In [3]:
x = np.matrix(var_originals);x
#x = np.asarray(x);x

#Padronizando para media 0 e variancia 1
z_score_A = (var_originals-var_originals.mean())/var_originals.std(axis=0)
#z_score_A
#Padronizando para media qualquer e variancia 1
z_score_B = var_originals/var_originals.std(axis=0)
#z_score_B

## Matriz de correlação

In [4]:
correlation = z_score_B.corr()

## Obtendo os Autovetores e Autovalores

In [5]:
#Transformando a matriz de correlacao do tipo pandas no tipo matrix
data_corr = np.asmatrix(correlation);data_corr
#Obtendo os Autovalores e autovetores
autovalues, autovectors = np.linalg.eig(data_corr)

## Proporçao da variancia total explicada pelo i-esimo componente principal

In [6]:
var_expl = autovalues/sum(autovalues);var_expl

array([0.77278095, 0.22721905])

## Porcentagem acumulada de variancia dos Yi

In [7]:
cum_var_expl = np.cumsum(var_expl)*100; cum_var_expl

array([ 77.27809539, 100.        ])

## Obtendo os scores

In [59]:
scores_met_matricial = np.matmul(autovectors.T, np.matrix(z_score_B).T)
#P = autovectors.T.dot(z_score_B.T)
#print(P.T)
scores_met_matricial = pd.DataFrame(scores_met_matricial.T, columns=[f"Componentes {i+1}" for i in range(len(autovectors))])
scores_met_matricial

Componentes 1  Componentes 2
0      22.159376     -12.322918
1      22.036354     -13.122063
2      20.248472     -13.895760
3      19.203615     -12.236124
4      20.847915     -12.958256

## Obtendo as variáveis originais pela transformação

In [63]:
z_score_B

A         B
0  24.382664  6.955426
1  24.860755  6.303355
2  24.143618  4.492046
3  22.231252  4.926760
4  23.904572  5.578831

In [90]:
print(scores_met_matricial)
print(autovectors)

   Componentes 1  Componentes 2
0      22.159376     -12.322918
1      22.036354     -13.122063
2      20.248472     -13.895760
3      19.203615     -12.236124
4      20.847915     -12.958256
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## Scores pela padronização normal (0,1)

In [94]:
scores_met_matricial_normal_padrao = np.dot(z_score_A, autovectors)
scores_met_matricial_normal_padrao

matrix([[ 1.26022964,  0.58410623],
        [ 1.13720737, -0.21503944],
        [-0.65067398, -0.98873568],
        [-1.69553148,  0.67090044],
        [-0.05123155, -0.05123155]])

## Valores reconstruídos para a normal (0,1)

In [95]:
np.dot(scores_met_matricial_normal_padrao, autovectors.T) + var_originals.mean().values

matrix([[100.47809144,  79.3041424 ],
        [100.95618289,  78.6520712 ],
        [100.23904572,  76.84076231],
        [ 98.32667995,  77.27547644],
        [100.        ,  77.92754764]])

## Exemplo por meio do pacote Scikit-learn

In [38]:
pca_ufrj = PCA(n_components=2)
pca_ufrj.fit(z_score_B)
scores = pca_ufrj.transform(z_score_B)

In [42]:
pca_ufrj.inverse_transform(z_score_B)

array([[  19.6619315 , -134.35585894],
       [  11.88375691, -129.40611147],
       [  -3.67259228, -109.6071216 ],
       [   6.22690266, -108.19290803],
       [   7.64111622, -119.50661653]])

In [19]:
import pandas as pd
from sklearn.decomposition import PCA

# Criar o DataFrame com os dados
var_originals = pd.DataFrame({"A": [102, 104, 101, 93, 100], "B": [96, 87, 62, 68, 77]})

# Instanciar a classe PCA
n_components = 2  # Número de componentes principais desejados
pca = PCA(n_components=n_components)

# Ajustar o modelo aos dados e obter os scores dos componentes principais
principal_components = pca.fit_transform(var_originals)

# Converter os scores dos componentes principais em um DataFrame
principal_components_df = pd.DataFrame(data=principal_components, columns=[f"Componente {i+1}" for i in range(n_components)])

print("Scores dos componentes principais:")
print(principal_components_df)


Scores dos componentes principais:
   Componente 1  Componente 2
0     18.073738      1.157581
1      9.558063     -2.375589
2    -15.582957     -3.764497
3    -11.064051      5.156237
4     -0.984793     -0.173731


Os resultados diferem do metodo manual devido a diferenças em como calcular as matrizes, os autovetores vsão obtidos com o sinal trocado

In [55]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Criar o DataFrame com os dados
var_originals = pd.DataFrame({"A": [102, 104, 101, 93, 100], "B": [96, 87, 62, 68, 77]})

z_score_B = var_originals/var_originals.std(axis=0)

# Padronizar os dados
#scaler = StandardScaler()
#var_standardized = scaler.fit_transform(var_originals)
var_standardized=z_score_B
# Instanciar a classe PCA
n_components = 2  # Número de componentes principais desejados
pca = PCA(n_components=n_components, svd_solver='randomized')

# Ajustar o modelo aos dados padronizados e obter os scores dos componentes principais
pca_1 = pca.fit(var_standardized)
principal_components = pca_1.transform(var_standardized)

# Converter os scores dos componentes principais em um DataFrame
principal_components_df = pd.DataFrame(data=principal_components, columns=[f"Componente {i+1}" for i in range(n_components)])

print("Scores dos componentes principais:")
print(principal_components_df)


Scores dos componentes principais:
   Componente 1  Componente 2
0     -1.260230     -0.584106
1     -1.137207      0.215039
2      0.650674      0.988736
3      1.695531     -0.670900
4      0.051232      0.051232


In [89]:
import numpy as np
import pandas as pd

# Criar o DataFrame com os dados
var_originals = pd.DataFrame({"A": [102, 104, 101, 93, 100], "B": [96, 87, 62, 68, 77]})

# Padronizar os dados manualmente
var_standardized = (var_originals - var_originals.mean()) / var_originals.std()

# Calcular a matriz de covariância
covariance_matrix = np.cov(var_standardized, rowvar=False)

# Calcular os autovetores e autovalores
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

# Ordenar os autovetores pelos autovalores em ordem decrescente
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvectors_sorted = eigenvectors[:, sorted_indices]

# Escolher o número de componentes principais desejados
n_components = 2
selected_eigenvectors = eigenvectors_sorted[:, :n_components]

# Calcular os scores dos componentes principais
principal_components = np.dot(var_standardized, selected_eigenvectors)

# Calcular os valores estimados (reconstruídos)
estimated_values = np.dot(principal_components, selected_eigenvectors.T) + var_originals.mean().values
print(principal_components)
print("Autovetores:")
print(selected_eigenvectors)

# Converter os valores estimados em um DataFrame
estimated_values_df = pd.DataFrame(data=estimated_values, columns=var_originals.columns)

print("Valores estimados (reconstruídos):")
print(estimated_values_df)


[[ 1.26022964  0.58410623]
 [ 1.13720737 -0.21503944]
 [-0.65067398 -0.98873568]
 [-1.69553148  0.67090044]
 [-0.05123155 -0.05123155]]
Autovetores:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Valores estimados (reconstruídos):
            A          B
0  100.478091  79.304142
1  100.956183  78.652071
2  100.239046  76.840762
3   98.326680  77.275476
4  100.000000  77.927548
