# Lista 1: PCA

In [127]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

## Questão 2

As 10 maiores empresas do mundo produzem os seguintes dados

1. Calcule o vetor de medias e a matriz de covariancias
2. Determine os componentes principais amostral e suas variâncias para esses
dados
3. Encontre a proporção da variância amostral total explicada por yˆ1
4. Calcule os coecientes de correlação. Que interpretação, se
houver, você pode dar ao primeiro componente principal?

### Solução

1. Calcule o vetor de médias e a matriz de covariâncias

In [128]:
BD_banks = pd.DataFrame({'vendas': [108.28,152.36,95.04,65.45,62.97,263.99,265.19,285.06,92.01,165.68],
                        'lucros': [17.05, 16.59, 10.91,14.14,9.52,25.33,18.54,15.73,8.10,11.13], 
                        'ativos': [1484.10,750.33,766.42,1110.46,1031.29,195.26,193.83,191.11,1175.16,211.15]})
#index=["Citigroup","General Electric","American Intl Group","Bank of America","HSBC Group", "ExxonMobil",
#                               "Royal Dutch/Shell","BP","ING Group","Toyota Motor"]

In [131]:
BD_banks

vendas  lucros   ativos
Citigroup            108.28   17.05  1484.10
General Electric     152.36   16.59   750.33
American Intl Group   95.04   10.91   766.42
Bank of America       65.45   14.14  1110.46
HSBC Group            62.97    9.52  1031.29
ExxonMobil           263.99   25.33   195.26
Royal Dutch/Shell    265.19   18.54   193.83
BP                   285.06   15.73   191.11
ING Group             92.01    8.10  1175.16
Toyota Motor         165.68   11.13   211.15

In [130]:
BD_banks.mean()
BD_banks.cov()

vendas       lucros         ativos
vendas   7476.453246   303.618620  -35575.959570
lucros    303.618620    26.190316   -1053.827393
ativos -35575.959570 -1053.827393  237054.269832

In [134]:
x=np.matrix(BD_banks)
S=np.cov(np.transpose(BD_banks))
S

array([[ 7.47645325e+03,  3.03618620e+02, -3.55759596e+04],
       [ 3.03618620e+02,  2.61903156e+01, -1.05382739e+03],
       [-3.55759596e+04, -1.05382739e+03,  2.37054270e+05]])

In [135]:
#Componentes principais
pca_banks = PCA(n_components=3)
pca_banks.fit(np.asarray(x))
pca_banks.transform(np.asarray(x))

array([[ 7.71541815e+02,  6.91972904e+01,  1.07824985e+00],
       [ 3.94514085e+01,  2.82956711e+00,  1.87390575e+00],
       [ 6.39664842e+01, -5.16895410e+01,  2.70674920e-02],
       [ 4.08541182e+02, -2.91666323e+01,  3.27039118e+00],
       [ 3.30656167e+02, -4.37772333e+01, -7.09377361e-01],
       [-5.26108468e+02,  3.04643264e+01,  6.19777699e+00],
       [-5.27671527e+02,  3.09697181e+01, -6.49881405e-01],
       [-5.33322878e+02,  4.99697107e+01, -4.79402286e+00],
       [ 4.68562332e+02,  6.30137190e+00, -4.94467565e+00],
       [-4.95616516e+02, -6.50985779e+01, -1.34943398e+00]])

In [136]:
pca.components_

array([[ 0.6364391 ,  0.51558083, -0.57369128],
       [-0.11086829,  0.79719669,  0.59345232],
       [ 0.76331743, -0.31409209,  0.56452871]])

In [138]:
np.round(pca_banks.explained_variance_ratio_,2)

array([0.99, 0.01, 0.  ])

In [149]:
# Respondendo a letra b
autovalues, autovectors = np.linalg.eig(np.matrix(S))
autovectors

matrix([[ 0.14970488,  0.98637086, -0.06827133],
        [ 0.00448559,  0.06837121,  0.99764987],
        [-0.98872055,  0.14965929, -0.00581105]])

In [151]:
np.round(pca_banks.explained_variance_ratio_,3)


array([0.991, 0.009, 0.   ])

In [152]:
pca_banks.fit_transform(np.asarray(x))

array([[ 7.71541815e+02,  6.91972904e+01,  1.07824985e+00],
       [ 3.94514085e+01,  2.82956711e+00,  1.87390575e+00],
       [ 6.39664842e+01, -5.16895410e+01,  2.70674920e-02],
       [ 4.08541182e+02, -2.91666323e+01,  3.27039118e+00],
       [ 3.30656167e+02, -4.37772333e+01, -7.09377361e-01],
       [-5.26108468e+02,  3.04643264e+01,  6.19777699e+00],
       [-5.27671527e+02,  3.09697181e+01, -6.49881405e-01],
       [-5.33322878e+02,  4.99697107e+01, -4.79402286e+00],
       [ 4.68562332e+02,  6.30137190e+00, -4.94467565e+00],
       [-4.95616516e+02, -6.50985779e+01, -1.34943398e+00]])