In [2]:
import pandas as pd
import numpy as np 

In [7]:
empresa = pd.DataFrame({"ganhoBruto": [9893,8776,13572,6455,5129,5432,3807,3423,3708,3294,5433,6287], 
                        "liquido": [564,389,1103,743,203,215,385,187,127,297,432,451], 
                        "patrimonio": [17689,17359,18597,8745,14397,3467,4679,6754,2275,6754,5589,8972]}, 
                        index=["Empresa 1","Empresa 2","Empresa 3","Empresa 4","Empresa 5","Empresa 6",
                               "Empresa 7","Empresa 8","Empresa 9","Empresa 10","Empresa 11","Empresa 12"])

In [26]:
#Covariancia
S=empresa.cov()
S

ganhoBruto        liquido    patrimonio
ganhoBruto  9.550609e+06  706121.060606  1.497823e+07
liquido     7.061211e+05   76269.515152  9.339151e+05
patrimonio  1.497823e+07  933915.060606  3.440811e+07

In [24]:
#autovalores e autovetores
autovalores,autovetores = np.linalg.eig(S)


In [12]:
autovalores

array([4.14743915e+07, 2.53950713e+06, 2.10925256e+04])

In [15]:
autovetores

array([[ 0.42509725,  0.8997068 ,  0.09909593],
       [ 0.02766083,  0.09651661, -0.99494694],
       [ 0.90472493, -0.42569029, -0.01614231]])

In [16]:
var_expl = autovalores/sum(autovalores);var_expl

array([9.41850797e-01, 5.76702086e-02, 4.78994659e-04])

In [23]:
#Scores
scores = np.matmul(autovetores.T, np.matrix(empresa).T).T
pd.DataFrame(scores)

0            1           2
0   20224.767165  1425.199249  133.664639
1   19446.533662   543.814143  202.417162
2   22625.099378  4400.716235  -52.695049
3   10676.374297  2156.657672 -240.745849
4   15211.263820 -1494.474013   73.887955
5    5451.756691  3432.090178  268.410116
6    5862.202619  1470.537827  -81.326234
7    7570.792668   222.632783   44.125128
8    3638.022756  2379.925017  204.365696
9    7518.997813   117.187433  -78.102411
10   7378.010497  2550.619202   18.351742
11  10802.253556  1880.692384   29.466238